CREATE TABLE IF NOT EXISTS coffeeshops (id LONG PRIMARY KEY, name VARCHAR(50) NOT NULL, address VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS users (id LONG PRIMARY KEY, name VARCHAR(50) NOT NULL, birthday date NOT NULL);
CREATE TABLE IF NOT EXISTS reviews (user_id LONG NOT NULL, shop_id LONG NOT NULL, review VARCHAR(50));









